export { default as Home } from './Home';
export { default as NotFound } from './NotFound';
export { default as Problems } from './Problems';
export { default as Profile } from './Profile';
export { default as SignIn } from './SignIn';
export { default as SignUp } from './SignUp';
export { default as Solutions } from './Solutions';
export { default as SolutionDetail } from './SolutionDetail';
export { default as MyPage } from './MyPage';
